'use client'
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from "./theme";
import Navbar from "./_components/Navbar/page";
import { store } from "@/lib/store";
import { Provider } from "react-redux";
import { Toaster } from "react-hot-toast";
import Footer from "./_components/footer/page";




const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className=''
      >

        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <Provider store={store}>
            <Navbar/>
          {children}
          <Footer/>
          <Toaster/>
              
            </Provider>
          
          </ThemeProvider>
        
        </AppRouterCacheProvider>
       
      </body>
    </html>
  );
}
